# Generated by Django 3.0.6 on 2020-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restrotable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('contactNo', models.CharField(max_length=500)),
                ('emailAddress', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=500)),
                ('menu', models.CharField(max_length=500)),
                ('Ratings', models.CharField(max_length=20)),
                ('Table2', models.CharField(max_length=500)),
                ('Table4', models.CharField(max_length=500)),
                ('Table6', models.CharField(max_length=500)),
            ],
        ),
    ]
